# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180118_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='updatedby',
            field=models.CharField(default='Andras', max_length=255),
            preserve_default=False,
        ),
    ]
